FROM python:3.10.7-slim-buster

WORKDIR /usr/src/stations_server

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY requirements.txt /usr/src/stations_server/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/stations_server

RUN chmod u+x ./entrypoint.sh