"""Added the time field to the table reset_password_tokens

Revision ID: 724f8c7d3e54
Revises: 1aa27ab9137b
Create Date: 2023-05-23 15:26:18.220952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724f8c7d3e54'
down_revision = '1aa27ab9137b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reset_password_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reset_password_tokens', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
